# basic options
title: Bizness Analytics 
author: R Richa
email: rashmi.richa@biznessanalytics.com
description: A blogging site for anlytics
twitter_username: BiznessAnalytics
github_username: richa-biznessanalytics  

# Build settings
markdown: kramdown
theme: jekyll-theme-cayman
